version: '2'
services:
  docs:
    build: .
    command: "jekyll serve --incremental"
    working_dir: "/code/bootstrap"
    volumes:
      - .:/code
    ports:
      - "9001:9001"
  # watcher:
  #   build: .
  #   command: "grunt watch"
  #   working_dir: "/code/bootstrap"
  #   volumes:
  #     - .:/code
