version: 2
jobs:
  build:
    working_directory: ~/architizer/design-kit/.
    docker:
    - image: circleci/node:4
    steps:
    - checkout

    # Install dependencies, or restore from cache
    - restore_cache:
        keys:
        - v1-dep-{{ checksum "package-lock.json" }}
        - v1-dep-
    - run: npm install
    - save_cache:
        key: v1-dep-{{ checksum "package-lock.json" }}
        paths:
        - ./node_modules

    # Build design kit
    - run: npm run build
    - run: ./node_modules/gulp/bin/gulp.js docs
    - run: ./node_modules/gulp/bin/gulp.js createAdkTemplatesList
    - run: echo 'No Tests'
    - run:
        name: Remove node_modules directory before persisting design-kit directory in CircleCI
        command: rm -rf ./node_modules

    - persist_to_workspace:
        root: ~/architizer
        paths:
          - design-kit

  deploy:
    working_directory: ~/architizer/
    docker:
      - image: architizer/docker-aws-eb:latest
    steps:
      - checkout
      - attach_workspace:
          at: ~/architizer/
      - run:
          name: Deploy directory to S3
          command: |
            cd design-kit
            bash -x deploy.sh

  publish:
    working_directory: ~/architizer/
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - attach_workspace:
        at: ~/architizer/
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - run:
        name: Publish package on npm registry
        command: |
          cd design-kit
          bash -x publish.sh


workflows:
  version: 2
  build-deploy-publish:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
